### ISSUE TITLE
Building- Sign Permit 

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#30] opened 2019-02-13 15:54 UTC
Allowed site inspection to be completed on sign permit, prior to electrical inspection being issued, site inspection should occur after electrical permit is issued and passes final inspection- this is only a requirement if the sign requires and electrical permit 
![image](https://user-images.githubusercontent.com/4129185/52725216-bf194580-2f7e-11e9-962f-a4c7970c70c1.png)

**Comment by imazlout** [comment] 2019-02-21 02:02
Training Needed. Duplicate of Issue #68 and #80

**Comment by dhenry-KCI** [comment] 2019-03-13 15:57
AP - 237355 with same issue

Logged by A. White.

**Comment by ABonomo21** [comment] 2019-04-08 14:26
Closed-Marked as Training Issue under duplicate issue #68 and #80 -MCoffman

**Closed by ABonomo21** 2019-04-08 14:26 UTC
Labels: Duplicate, Training Issue
