### ISSUE TITLE
Use Home Occupation and Land Use- Inspection Rules

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1427] opened 2019-08-06 13:27 UTC
transfer inspection rules for use permits 

![image](https://user-images.githubusercontent.com/47611580/62543710-6d19f400-b82c-11e9-9fd1-c541e0e377e9.png)

**Comment by ABonomo21** [comment] 2019-08-07 16:23
![image](https://user-images.githubusercontent.com/47611580/62639709-197fd700-b90e-11e9-9b9b-16cd28410c65.png)

**Comment by JuanitaMiles** [comment] 2019-08-19 19:21
There appears to be an overall data issue that is preventing inspections from automatically assigning to an inspector. Inspection assignments were setup based on Election Districts and Martin has set up the majority of these inspections based on the rules provided. However, when viewing the parcel details associated to various addresses, the Elec Dist field does not represent an actual election district. Instead it appears to be set equal to the Tax Map field.

I've confirmed with Ashlye that there are under 30 election districts, therefore something like "0108A" does not appear accurate.

@dhenry-KCI we need to understand if this is a GIS issue and when it will be corrected to be able to test this inspection assignment functionality.

![image](https://user-images.githubusercontent.com/31770504/63292960-e1c14980-c294-11e9-9f6d-4e6ee34fb4a3.png)

**Comment by dhenry-KCI** [comment] 2019-08-21 17:06
Duplicate of #1490 tracking progress there. Issue is that Election District is pulling frm Tax Map. GIS needs to populate this attribute and IPS needs to pull from correct field.

**Closed by dhenry-KCI** 2019-08-21 17:06 UTC
Labels: Bug, County Fix, Retest Failed
