### ISSUE TITLE
Building - ZoningCert - Inspection

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#79] opened 2019-02-20 17:01 UTC
For the same zoning certificate: the site inspection failed twice and the re-inspection fee did not generate. After two failed inspections of the same type, the $48 re-inspection fee should generate.

AP - 237190
Logged by A.White 2/15

![image](https://user-images.githubusercontent.com/4129185/53109504-08c9d900-3507-11e9-9c0c-18d24ceab50f.png)

**Comment by imazlout** [comment] 2019-02-21 01:30
This is a duplicate of Issue #89. Sent email to @ABonomo21 and awaiting response on how to proceed.

**Comment by JuanitaMiles** [comment] 2019-03-02 04:15
Closing this issue as it is a duplicate of #89

**Closed by JuanitaMiles** 2019-03-02 04:15 UTC
Labels: Duplicate
