### ISSUE TITLE
License - Liquor License - RENEWAL_CK Review Milestone Progression

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1015] opened 2019-05-30 16:17 UTC
Approving my RENEWAL_CK review results in skipping all of the fee/renewal milestones mentioned in issue #1013 and just generates another RENEWAL_CK review.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58647110-d46b7300-82d4-11e9-925e-a96395c33ecd.png)

![image](https://user-images.githubusercontent.com/31770504/58647120-da615400-82d4-11e9-97e8-becd02fa751e.png)

**Comment by calequin** [comment] 2019-05-31 02:04
The issue is that fees are not being added. Part of the review is to manually add the correct fees to the application. From my understanding the board would be adding fees manually prior to accepting the review.

**Comment by calequin** [comment] 2019-06-11 20:52
fixed in preprod and test

**Comment by JuanitaMiles** [comment] 2019-06-17 13:10
Appears fixed. If fees are added during the Renewal Review milestone the application progresses to Awaiting Renewal Fee Payment. If no fees are added, the application progresses to Active.

@JuanitaMiles Add SOP language to the Renewal Review Milestone to remind users that Fees must be manually added.

**Comment by JuanitaMiles** [comment] 2019-06-17 13:34
I have added SOP language to the Renewal Review milestone in PreProd and TEST. -JM

![image](https://user-images.githubusercontent.com/31770504/59607934-4ec43180-90e2-11e9-966e-81c1379a482c.png)

![image](https://user-images.githubusercontent.com/31770504/59608272-ffcacc00-90e2-11e9-8098-8384ae35db18.png)

**Closed** 2019-06-20 18:15 UTC
Labels: Ready for PreProd Env. Retest, Training Issue
