### ISSUE TITLE
Building Permit - Trailer - COO

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1547] opened 2019-08-12 19:38 UTC
Get an error when trying to run the on demand COO for trailer
![image](https://user-images.githubusercontent.com/47611580/62892839-30ac3380-bd17-11e9-9529-3ced8c3c3d0a.png)

**Comment by ABonomo21** [comment] 2019-08-12 19:44
did not get a notification

**Comment by dhenry-KCI** [comment] 2019-08-13 13:27
@TaraF see issue. Let me know if these are issues that should be assigned to Martin.

**Comment by dhenry-KCI** [comment] 2019-09-18 03:10
SSRS issue - duplicate of #1411

**Closed** 2019-09-18 03:10 UTC
Labels: Duplicate, Reporting
