### ISSUE TITLE
License - Liquor License - License Renewal Attachments

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1149] opened 2019-06-13 17:33 UTC
Applicants have the ability to begin applying for a license renewal at a certain date. They will be able to upload their renewal application on R4C. How will the County know when the renewal application has been submitted on R4C. Will there be an alert to the County or will they have to continuously check the application to see if the application has been attached?

Was there a previously discussed strategy for renewal submittals?

**Comment by megisys** [comment] 2019-06-14 14:23
It is a formula on AfterAdd on the Attachment object. We can work on this together

Dan

**Comment by calequin** [comment] 2019-06-22 14:46
The county will know when an item has been resubmitted since the milestone will progress to resubmitall review and it will fall on their dashboard.

**Comment by dhenry-KCI** [comment] 2019-06-26 17:48
confirmed training issue. Closing issue

**Closed by dhenry-KCI** 2019-06-26 17:48 UTC
Labels: Training Issue
