### ISSUE TITLE
Building - ResBldg - Related Records

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#62] opened 2019-02-20 15:03 UTC
The parent structure permit issued without any of the units being attached. The parent structure and the units need to be issued together. There should be a red line in the check status stage to be able to stop the progression of the permit until the number of units that was input in the parent structure are attached.

AP - 237223
Logged by A.White 2/19

![image](https://user-images.githubusercontent.com/4129185/53100854-92bd7600-34f6-11e9-8dfe-f9e42f1d2f9e.png)

**Comment by imazlout** [comment] 2019-02-20 23:39
This is an enhancement as it wasn't mentioned that this needed to be configured. On which milestone should I add this Status Check for the Parent Permit: "Unit RESBLDG Permit must be related as a Child Building Application" ? 
@dhenry-KCI @ABonomo21

**Comment by ABonomo21** [comment] 2019-02-21 16:17
I would think the check status stage needs to occur at a Pre-Issue Permit milestone. The parent and all related child permits all need to be at the pre-issue milestone and then release concurrently.

**Comment by imazlout** [comment] 2019-02-21 18:57
Ok, will add the status check on Pending Issuance milestone on the parent permit

**Comment by dhenry-KCI** [comment] 2019-02-21 20:16
@imazlout Yes

**Comment by imazlout** [comment] 2019-02-21 21:25
Ready for test once updates are copied to TEST.
Number of child permits of parent structure must equal number on detail page

Please screenshot for proof of test (Parent: AP# 236145 Units AP#236147 and AP#236146 in DEV)

**Before adding all children:**
<img width="960" alt="issue62_beforeaddingallchilds" src="https://user-images.githubusercontent.com/47784290/53202657-152c5f80-35f5-11e9-85f4-baa2dd2a1b17.png">

**After adding all children:**
<img width="960" alt="issue62_afteraddingallchilds" src="https://user-images.githubusercontent.com/47784290/53202656-152c5f80-35f5-11e9-9a37-b896f6ffc50a.png">

**Comment by dhenry-KCI** [comment] 2019-03-06 15:23
This issued is half fixed. The Parent Structure #238582 stopped at the status of Pending Issuance until the ResBldg Unit permits were attached. However once those two permits for the Units #238583 & #238584 were attached to the parent structure, that permit issued even though the two units were not yet issued. The Parent can not be issued until the units are ready for issuance as well. They all need to be issued at the same time-AW

![image](https://user-images.githubusercontent.com/4129185/53892166-c66dc500-3ff9-11e9-9461-4f1f2b089bb0.png)

![image](https://user-images.githubusercontent.com/4129185/53892188-cff72d00-3ff9-11e9-8617-59aca5f1005c.png)

**Comment by imazlout** [comment] 2019-03-06 16:33
Ready for test. 
Made update so that it looks that the child permits attached have an issued date.

**Comment by ABonomo21** [comment] 2019-03-11 15:35
Issue Partially Fixed-Parent Structure permit #238717 stopped at the Pending Issuance Milestone(as it should). The once the unit permits #238720 & #238722 paid their fees and completed their reviews, they stopped at the Pending Issuance Milestone too, stating "Parent Structure must be issued". While they are all stopping at the correct milestone, it seems like they are stuck in a loop of which one should be issued first.-AW
Parent Structure- #238717
![image](https://user-images.githubusercontent.com/47611580/54136049-6314d600-43f1-11e9-9718-a3585f3e6897.png)
![image](https://user-images.githubusercontent.com/47611580/54136090-7a53c380-43f1-11e9-8bc2-e0ffdd6044f8.png)

Unit 1- #238720
![image](https://user-images.githubusercontent.com/47611580/54136144-98b9bf00-43f1-11e9-8326-f18b55056fd1.png)
![image](https://user-images.githubusercontent.com/47611580/54136172-a7a07180-43f1-11e9-8f0b-06a771060ef7.png)

Unit 2- #238722
![image](https://user-images.githubusercontent.com/47611580/54136228-c1da4f80-43f1-11e9-8cd0-ff4a1289a252.png)
![image](https://user-images.githubusercontent.com/47611580/54136255-cd2d7b00-43f1-11e9-9700-82a10adf5c10.png)

**Comment by imazlout** [comment] 2019-03-12 17:02
@ABonomo21 You're right, if we want to keep the status check, then one of them has to be removed otherwise it's in an infinite loop. My question to you is which one? Should we prevent the Unit(s) from issuing until the permit is issued? or should we prevent the Parent from issuing until the Unit(s) are issued?

**Comment by imazlout** [comment] 2019-03-15 06:16
Per Ashley's comment #65, removing criteria that child permit has to be issued before Parent, since she confirmed that Parent should issue first. Now the formula is such that as long as the count of attached is correct, the status check passes. Not sure if this would be ready for retest or training, so marked as both. Please re-categorize as you see fit.

**Comment by ABonomo21** [comment] 2019-03-19 14:11
Testing Failed-AW-The parent structure has the two units attached but it is still stuck in the pending issuance stage. the parent permit is also stating that the "Parent permit must be issued" even though this is the parent permit. The child units are stuck in the pending issuance stage stating "Parent permit must be issued" (this part is correct), but it is also stating that "Unit RESBLDG must be related as a Child Building Application". This is not required for the child/unit permits, only for the parent.

Parent Structure #238922
![image](https://user-images.githubusercontent.com/47611580/54612179-d7252e80-4a2e-11e9-80a0-8405ef331e43.png)

![image](https://user-images.githubusercontent.com/47611580/54612238-f328d000-4a2e-11e9-8189-c7bd36b51e98.png)

![image](https://user-images.githubusercontent.com/47611580/54612281-09369080-4a2f-11e9-9415-f4d4f02fb776.png)

Unit 1- #238923
![image](https://user-images.githubusercontent.com/47611580/54612334-22d7d800-4a2f-11e9-81c7-bb5bf3891b8c.png)

Unit 2- #238924
![image](https://user-images.githubusercontent.com/47611580/54612406-49960e80-4a2f-11e9-825d-35e1431b2669.png)

**Comment by megisys** [comment] 2019-04-03 13:15
Ready

**Comment by ABonomo21** [comment] 2019-04-04 14:23
Fixed, Parent Structure and units issued in correct order-AW

![image](https://user-images.githubusercontent.com/47611580/55563315-b235ea00-56c3-11e9-927e-3aefe639b3cb.png)

**Closed by ABonomo21** 2019-04-04 14:23 UTC
Labels: Ready For Retest
