### ISSUE TITLE
Rhythm for Civics - Applicant Email Error (Excel Issue #2)

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#527] opened 2019-03-22 00:06 UTC
The system did not require the additional applicant (contractor) to provide their email.

Logged by: G.Hessong
Logged date: 3.21.2019

![image](https://user-images.githubusercontent.com/4129185/54792409-5aec4000-4c14-11e9-84bc-9aa2f040daf5.png)

**Comment by calequin** [comment] 2019-04-23 15:16
Error message now populates to show additional applicants need an email
![image](https://user-images.githubusercontent.com/47603568/56592735-3b508a80-65b9-11e9-889d-e3ce2314b807.png)

**Comment by calequin** [comment] 2019-05-06 18:04
duplicate of the applicant invitation issue

**Closed by calequin** 2019-05-06 18:04 UTC
Labels: 19.7, Duplicate, Enhancement, R4C
