### ISSUE TITLE
Building- Retaining Wall - Incorrect Review Population 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#48] opened 2019-02-14 20:18 UTC
Retaining Wall Permit #237171-The DUSWMF review generated even though it is not required for this permit/property.

![image](https://user-images.githubusercontent.com/47611580/52815115-cc602e00-306b-11e9-95f3-dd90dd890d7f.png)

**Comment by imazlout** [comment] 2019-02-21 02:54
Duplicate of #36. Sent email to @ABonomo21  and awaiting reply

**Comment by dhenry-KCI** [comment] 2019-02-26 20:31
Confirmed fixed

**Closed by dhenry-KCI** 2019-02-26 20:31 UTC
Labels: Duplicate
