### ISSUE TITLE
Building - Resuse - Pole Building

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#100] opened 2019-02-21 03:52 UTC
THe system should not generate a DUSWM review for Pole Buildings

AP237170
Logged by M. Coffman

![polebuilding](https://user-images.githubusercontent.com/4129185/53142510-3001c400-3562-11e9-943c-6d82db855051.png)

**Comment by imazlout** [comment] 2019-02-21 21:49
Duplicate of #36

**Comment by ABonomo21** [comment] 2019-04-08 15:26
fixed-AW-(this was not a duplicate of #36)
![image](https://user-images.githubusercontent.com/47611580/55736383-30123200-59f1-11e9-888d-d9f162b9dec0.png)

**Closed by ABonomo21** 2019-04-08 15:26 UTC
Labels: Duplicate, Enhancement
