### ISSUE TITLE
Building Permit - Awaiting Fee Payment Notification - Standard Format

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1488] opened 2019-08-08 18:10 UTC
Awaiting payment notification needs to be cleaned up 
![image](https://user-images.githubusercontent.com/47611580/62726874-3982c980-b9e6-11e9-8a3e-271230914599.png)

**Comment by ABonomo21** [comment] 2019-08-08 18:12
not sure why the comments are filtering under the if you prefer line..

**Comment by dhenry-KCI** [comment] 2019-08-08 18:22
@ABonomo21 - Looking at the notification I will tell Martin to do the following:
1. Need to martin to remove the extra "0" after the payment amount. 
2. I am assuming you want the comment removed. 
3. There appears to be an extra "space" after LLC

is this correct? Anything else?

**Comment by mmbanong** [comment] 2019-08-15 15:01
Requested changes have been made to Building Permit - Awaiting Fee Payment Notification

![Building Permit - Awaiting Fee Payment Notification](https://user-images.githubusercontent.com/47392173/63103978-160ed000-bf4c-11e9-8dea-4b9f17453649.PNG)

**Comment by megisys** [comment] 2019-09-05 13:55
Closing due to Duplicate of updates to this notification template

**Closed by megisys** 2019-09-05 13:55 UTC
Labels: Ready for Test Env. Retest
