### ISSUE TITLE
License - Liquor License - COMPLETE Review Resubmit (2nd RESUBMIT)

### ISSUE THREAD

**Issue by JuanitaMiles** [kcigeospatial/Fred_Co_Land-Management#1005] opened 2019-05-30 15:22 UTC
When a Completeness Check Review is resulted with RESUBMIT a second time, the application does not stop in the Awaiting More Information milestone. It immediately generates a third Complete Review.

The Logs tab shows only receiving one RESREC event log (from the first resubmittal), and the Status Logs show that the application blew through the second Awaiting More Information milestone and went straight back to Completeness Check.

I have confirmed this issue occurs in both TEST and PreProd environments.

![image](https://user-images.githubusercontent.com/31770504/58643194-d0d3ee00-82cc-11e9-8ab3-376813072ad1.png)

![image](https://user-images.githubusercontent.com/31770504/58643210-da5d5600-82cc-11e9-9422-5ed2511e6102.png)

**Comment by calequin** [comment] 2019-06-11 21:00
fixed in preprod and test

**Comment by JuanitaMiles** [comment] 2019-06-12 17:39
The application goes through the Awaiting More Information loop, however the Applicant Actions detail page stays populated with 'Yes'. Typically the form clears each time you go into the Awaiting More Information milestone. I don't know if this being pre-populated will impact Rhythm for Civics.

![image](https://user-images.githubusercontent.com/31770504/59373364-806e7e80-8d17-11e9-8ee8-fe7e2da7ba15.png)

![image](https://user-images.githubusercontent.com/31770504/59373318-6e8cdb80-8d17-11e9-9717-feecd4b0f12c.png)

**Comment by calequin** [comment] 2019-06-12 18:02
fixed

**Comment by JuanitaMiles** [comment] 2019-06-17 12:03
The Applicant Actions detail page is still pre-populating with 'Yes' after the second COMPLETE review resubmit. 

Tested this in PreProd.

![image](https://user-images.githubusercontent.com/31770504/59603013-4a921700-90d6-11e9-956c-63e34c343140.png)


![image](https://user-images.githubusercontent.com/31770504/59602994-36e6b080-90d6-11e9-8f0b-cbaeb1f6a3d3.png)

**Comment by kellyjj** [comment] 2019-06-19 13:49
assigning to myself.  will work on this

**Comment by kellyjj** [comment] 2019-06-19 14:18
this seems to be working as expected.   will reassign and remove bug label.

**Comment by JuanitaMiles** [comment] 2019-06-20 18:48
Penny tested in Test and the Applicant Actions detail page is still auto-populating with "Yes"

**Comment by goggansd** [comment] 2019-06-21 16:46
Could not replicate the issue. Likely the user needs to disable Autocomplete in the web browser.

![image](https://user-images.githubusercontent.com/28841997/59938279-8f91b280-9422-11e9-98b7-bf67f276c9b9.png)

**Comment by dhenry-KCI** [comment] 2019-06-27 17:21
confirmed closed.

**Closed by dhenry-KCI** 2019-06-27 17:21 UTC
Labels: Ready for Test Env. Retest
