### ISSUE TITLE
PDox - Due Dates

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1563] opened 2019-08-13 17:29 UTC
why are the initial due dates when assigning reviewers off by one day - assigned for 1 week and only did 6 days.
![image](https://user-images.githubusercontent.com/47611580/62963068-40d31a00-bdce-11e9-84fa-e7cf7c1a50b5.png)
once assigned it changes to the correct date
![image](https://user-images.githubusercontent.com/47611580/62963131-66f8ba00-bdce-11e9-8655-63c84d8ee6ea.png)

**Comment by dhenry-KCI** [comment] 2019-08-21 13:51
duplicate of issue #1292. Closing this issue.

**Closed by dhenry-KCI** 2019-08-21 13:51 UTC
Labels: Bug, ProjectDox
