### ISSUE TITLE
Plumbing Official Issuance - Missing 

### ISSUE THREAD

**Issue by ABonomo21** [kcigeospatial/Fred_Co_Land-Management#1533] opened 2019-08-12 16:57 UTC
Official plumbing issuance does not generate for me once issued but does for Juanita- 
![image](https://user-images.githubusercontent.com/47611580/62882843-c25c7680-bd00-11e9-9a7f-5b28c2f3a125.png)

**Comment by dhenry-KCI** [comment] 2019-09-05 16:14
Duplicate of issue #1631

**Closed by dhenry-KCI** 2019-09-05 16:14 UTC
Labels: Duplicate, Reporting
