### ISSUE TITLE
R4C - Planning - Verification Letter (LOR) - Town

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#1021] opened 2019-06-03 13:38 UTC
I was able to apply for a LOR for a town parcel.
![image](https://user-images.githubusercontent.com/4129185/58805741-ab9ff200-85e2-11e9-9441-6a0046652859.png)
-GH

**Comment by calequin** [comment] 2019-06-14 19:45
duplicate of outside frederick parcel. marking as duplicate

**Closed** 2019-08-21 17:38 UTC
Labels: Duplicate
