### ISSUE TITLE
Building - RESBLD - Child Building Permit

### ISSUE THREAD

**Issue by dhenry-KCI** [kcigeospatial/Fred_Co_Land-Management#92] opened 2019-02-21 02:32 UTC
System allowed use to issue and close first townhouse without other townhouses being added as a child permit.

![townhosue_child 2](https://user-images.githubusercontent.com/4129185/53140064-8e767480-3559-11e9-8e88-38ff6333e1fc.png)
![townhouse_child](https://user-images.githubusercontent.com/4129185/53140065-8e767480-3559-11e9-98a5-686042b86078.png)

**Comment by imazlout** [comment] 2019-02-21 02:38
Related to #78. Sent email to @ABonomo21 and awaiting response

**Comment by imazlout** [comment] 2019-02-21 18:56
Will add status check on Pending Issuance similar to config on #62

**Comment by imazlout** [comment] 2019-02-21 21:25
Ready for test once updates are copied to TEST.
Number of child permits of initial structure must equal number on detail page

Please screenshot for proof of test (Initial: AP# 236160 Units AP#236161 and AP#236162 in DEV)

**Before adding all children:**
<img width="960" alt="issue92_beforeaddingallchilds" src="https://user-images.githubusercontent.com/47784290/53202720-3d1bc300-35f5-11e9-92d8-2d6e94f2d8c7.png">

**After adding all children:**
<img width="960" alt="issue92_afteraddingallchilds" src="https://user-images.githubusercontent.com/47784290/53202728-4442d100-35f5-11e9-8c12-6b1c9afecaab.png">

**Comment by dhenry-KCI** [comment] 2019-02-22 15:13
Confirmed fixed.
![1](https://user-images.githubusercontent.com/4129185/53251384-836f3180-368a-11e9-8f4f-94c60798a2c3.jpg)

**Comment by dhenry-KCI** [comment] 2019-02-22 15:14
confirmed fixed

**Comment by dhenry-KCI** [comment] 2019-02-22 16:12
This issued is half fixed. The first townhouse does have the hold to not issue until there is the child RESBLDG permits attached and this part is correct. But after adding the correct amount of child permits, the first permit does not recognize the correct amount of houses because it is not including itself.  For a row of three townhomes (like these example permits) the first permit would also be the first house, so there should be two child permits attached to it to make the total of 3.
![1](https://user-images.githubusercontent.com/4129185/53255041-caf9bb80-3692-11e9-825c-b458ac358071.jpg)
![3](https://user-images.githubusercontent.com/4129185/53255042-caf9bb80-3692-11e9-85e1-fee5260a81a2.jpg)
![4](https://user-images.githubusercontent.com/4129185/53255043-caf9bb80-3692-11e9-8c2a-9078c4024009.jpg)

**Comment by dhenry-KCI** [comment] 2019-02-22 16:15
This is half fixed. The Hold does generate to stop the first permit from issuing until the other RESBLDG permits have been attached and that is correct. But the first permit is not including itself as the first house in the row. So for this row of three townhouses, the first permit is the first house and the the two child permits are the other two. Making a total of three.

![1](https://user-images.githubusercontent.com/4129185/53255082-e664c680-3692-11e9-9efa-798847d46811.jpg)
![3](https://user-images.githubusercontent.com/4129185/53255083-e664c680-3692-11e9-9356-a588d3e67f10.jpg)
![4](https://user-images.githubusercontent.com/4129185/53255084-e664c680-3692-11e9-8a52-e558bedf430d.jpg)

**Comment by imazlout** [comment] 2019-03-01 16:48
Ready for test.

Updated formula RESBLDG_UnitPermitRelated_SCF to count =1 initially so that it counts itself (the parent) as one

I tested with APPLICATION# 237336 created by the tester. The status check has been satisfied now and application moved to Permit Issued, then Inspections milestone as expected.

**Comment by ABonomo21** [comment] 2019-03-05 16:24
Issue of not counting the parent as one of the townhouse permits was corrected, however this issue is not completely corrected-mc

A/P 238520-Requires Child Townhouse permits-Correct 
![image](https://user-images.githubusercontent.com/47611580/53817918-0454e580-3f35-11e9-9deb-dfe901c869da.png)

Only One Child Townhouse permit in pending issuance (238521)added-Parent Permit (238520) Still Pending issuance- Correct
![image](https://user-images.githubusercontent.com/47611580/53819219-7dedd300-3f37-11e9-967e-8e7c9e3f8ae6.png)
![image](https://user-images.githubusercontent.com/47611580/53819302-afff3500-3f37-11e9-9db7-354a39c229d0.png)

Added Second Child Townhouse permit in completeness check status (238522) and First Child Permit (238521) is pending issuance-Parent Permit (238520) issued without both permits being issued-All of the townhouse permits must issue at the same time, they can not issue without the others being issued-NOT Corrected
![image](https://user-images.githubusercontent.com/47611580/53820082-205a8600-3f39-11e9-8d4c-9cf9edb34e10.png)

**Comment by megisys** [comment] 2019-03-05 17:00
@imazlout

**Comment by imazlout** [comment] 2019-03-05 18:45
@ABonomo21 I'm not checking for a status. I'm just checking that the count matches. To make sure I understand your request correctly, please confirm or correct the statement below.

For all child permits that need to be attached to the parent condo/townhouse, not only does the count need to be correct (count = children + parent), but all children must be Issued before the Parent can be issued?

**Comment by ABonomo21** [comment] 2019-03-06 15:22
@imazlout Yes this is correct-MCoffman

**Comment by imazlout** [comment] 2019-03-06 16:33
Ready for test. 
Made update so that it looks that the child permits attached have an issued date.

**Comment by ABonomo21** [comment] 2019-03-11 15:36
NOT Corrected-None of the permits are issuing-MCoffman

Permit# 238710- All of the Child Permits are attached and in the Pending Issuance stage however the Parent Permit is not issuing
![image](https://user-images.githubusercontent.com/47611580/54135800-de29bc80-43f0-11e9-8fb2-98d7a5afec32.png)

All of the Child Permits say they are waiting for the Parent Permit to be issued
![image](https://user-images.githubusercontent.com/47611580/54135913-1d580d80-43f1-11e9-86a4-911bf7cf0998.png)

The Parent Permit says it is waiting for the Child Permits to all be added, which they are, with the Parent Permit counting as the first townhouse in the row
![image](https://user-images.githubusercontent.com/47611580/54136058-6ad47a80-43f1-11e9-9001-9fbd800cb6ca.png)

![image](https://user-images.githubusercontent.com/47611580/54136108-82136800-43f1-11e9-937c-e6360c8ca374.png)

![image](https://user-images.githubusercontent.com/47611580/54136226-c1da4f80-43f1-11e9-943c-6ec7a19c8225.png)

**Comment by imazlout** [comment] 2019-03-12 17:03
@ABonomo21 You're right, if we want to keep the status check, then one of them has to be removed otherwise it's in an infinite loop. My question to you is which one? Should we prevent the Unit(s) from issuing until the permit is issued? or should we prevent the Parent from issuing until the Unit(s) are issued?

**Comment by imazlout** [comment] 2019-03-15 06:17
Per Ashley's comment #65, removing criteria that child permit has to be issued before Parent, since she confirmed that Parent should issue first. Now the formula is such that as long as the count of attached is correct, the status check passes. Not sure if this would be ready for retest or training, so marked as both. Please re-categorize as you see fit.

**Comment by ABonomo21** [comment] 2019-03-19 14:45
Testing Failed-AW-Same issues as #62 The parent structure (first townhouse) has the two other units attached but it is still stuck in the pending issuance stage. the parent permit is also stating that the "Parent permit must be issued" even though this is the parent permit. The child units are stuck in the pending issuance stage stating "Parent permit must be issued" (this part is correct), but it is also stating that "Unit RESBLDG must be related as a Child Building Application". This is not required for the child/unit permits, only for the parent.

Parent(first townhouse)- #238930
![image](https://user-images.githubusercontent.com/47611580/54614934-a09de280-4a33-11e9-8ba4-5c969b6b0dd7.png)

![image](https://user-images.githubusercontent.com/47611580/54615000-bca18400-4a33-11e9-9364-807727f60fa1.png)

![image](https://user-images.githubusercontent.com/47611580/54615065-d216ae00-4a33-11e9-927d-1069594b07c8.png)

Second Townhouse- #238931
![image](https://user-images.githubusercontent.com/47611580/54615157-fc686b80-4a33-11e9-9600-68a47b31733c.png)

Third Townhouse- #238932
![image](https://user-images.githubusercontent.com/47611580/54615205-0f7b3b80-4a34-11e9-867c-ce929c4ee69c.png)

**Comment by megisys** [comment] 2019-04-03 13:14
Ready for Retest

**Comment by ABonomo21** [comment] 2019-04-05 14:53
fixed!!-AW
![image](https://user-images.githubusercontent.com/47611580/55636538-0f4ba180-5791-11e9-83b6-09530f0d8ad0.png)
![image](https://user-images.githubusercontent.com/47611580/55636557-1672af80-5791-11e9-8d2c-d5427793d4b6.png)

**Closed by ABonomo21** 2019-04-05 14:53 UTC
Labels: Ready For Retest
